name: dress_experiments
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - asttokens=2.4.1
  - binutils_impl_linux-64=2.40
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.25.0
  - ca-certificates=2023.11.17
  - cairo=1.16.0
  - cffi=1.16.0
  - comm=0.2.1
  - cudatoolkit=11.2.2
  - cudnn=8.1.0.77
  - curl=8.1.2
  - debugpy=1.8.0
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.5.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gcc_impl_linux-64=13.2.0
  - gettext=0.21.1
  - gfortran_impl_linux-64=13.2.0
  - graphite2=1.3.13
  - gsl=2.7
  - gxx_impl_linux-64=13.2.0
  - harfbuzz=6.0.0
  - icu=72.1
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - ipython=8.20.0
  - jedi=0.19.1
  - jupyter_client=8.6.0
  - jupyter_core=5.7.1
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.1.2
  - libdeflate=1.18
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-devel_linux-64=13.2.0
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.1
  - libgomp=13.2.0
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libopenblas=0.3.25
  - libpng=1.6.39
  - libsanitizer=13.2.0
  - libsodium=1.0.18
  - libsqlite=3.44.2
  - libssh2=1.11.0
  - libstdcxx-devel_linux-64=13.2.0
  - libstdcxx-ng=13.2.0
  - libtiff=4.5.1
  - libuuid=2.38.1
  - libuv=1.44.2
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxml2=2.11.5
  - libxslt=1.1.37
  - libzlib=1.2.13
  - make=4.3
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - meme=5.5.4
  - mpi=1.0
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - nodejs=20.5.1
  - openmpi=4.1.6
  - openssl=3.2.0
  - packaging=23.2
  - pango=1.50.14
  - parso=0.8.3
  - pcre2=10.40
  - perl=5.32.1
  - perl-app-cpanminus=1.7047
  - perl-base=2.23
  - perl-business-isbn=3.007
  - perl-business-isbn-data=20210112.006
  - perl-carp=1.38
  - perl-cgi=4.56
  - perl-common-sense=3.75
  - perl-compress-raw-zlib=2.105
  - perl-config-general=2.65
  - perl-constant=1.33
  - perl-cpan-meta=2.150010
  - perl-cpan-meta-requirements=2.143
  - perl-cpan-meta-yaml=0.018
  - perl-data-dumper=2.183
  - perl-dbi=1.643
  - perl-digest-md5=2.58
  - perl-encode=3.19
  - perl-encode-locale=1.05
  - perl-exporter=5.72
  - perl-extutils-cbuilder=0.280230
  - perl-extutils-makemaker=7.70
  - perl-extutils-manifest=1.73
  - perl-extutils-parsexs=3.44
  - perl-file-path=2.18
  - perl-file-spec=3.48_01
  - perl-file-temp=0.2304
  - perl-file-which=1.24
  - perl-getopt-long=2.54
  - perl-html-parser=3.81
  - perl-html-tagset=3.20
  - perl-html-template=2.97
  - perl-html-tree=5.07
  - perl-http-date=6.06
  - perl-http-message=6.36
  - perl-io-html=1.004
  - perl-ipc-cmd=1.04
  - perl-json=4.10
  - perl-json-pp=4.11
  - perl-json-xs=2.34
  - perl-locale-maketext-simple=0.21
  - perl-log-log4perl=1.55
  - perl-lwp-mediatypes=6.04
  - perl-math-cdf=0.1
  - perl-mime-base64=3.16
  - perl-module-build=0.4231
  - perl-module-corelist=5.20220620
  - perl-module-load=0.34
  - perl-module-load-conditional=0.68
  - perl-module-metadata=1.000038
  - perl-params-check=0.38
  - perl-parent=0.236
  - perl-pathtools=3.75
  - perl-perl-ostype=1.010
  - perl-scalar-list-utils=1.62
  - perl-sys-info=0.7811
  - perl-sys-info-base=0.7807
  - perl-sys-info-driver-linux=0.7905
  - perl-test-nowarnings=1.06
  - perl-text-abbrev=1.02
  - perl-text-parsewords=3.31
  - perl-text-template-simple=0.91
  - perl-time-local=1.35
  - perl-timedate=2.33
  - perl-types-serialiser=1.01
  - perl-unix-processors=2.046
  - perl-uri=5.12
  - perl-url-encode=0.03
  - perl-version=0.9924
  - perl-xml-namespacesupport=1.12
  - perl-xml-parser=2.44_01
  - perl-xml-sax=1.02
  - perl-xml-sax-base=1.09
  - perl-xml-sax-expat=0.51
  - perl-xml-simple=2.25
  - perl-yaml=1.30
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.2.1
  - pixman=0.43.0
  - platformdirs=4.1.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.7
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.17.2
  - python=3.10.12
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytz=2023.3.post1
  - pyzmq=25.1.2
  - r-base=4.3.1
  - readline=8.2
  - rpy2=3.5.11
  - sed=4.8
  - setuptools=69.0.3
  - simplegeneric=0.8.1
  - six=1.16.0
  - stack_data=0.6.2
  - sysroot_linux-64=2.12
  - tk=8.6.13
  - tktable=2.10
  - tornado=6.3.3
  - traitlets=5.14.1
  - typing_extensions=4.9.0
  - tzlocal=5.2
  - wcwidth=0.2.13
  - wheel=0.42.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.3.0
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - alembic==1.13.0
      - attrs==23.1.0
      - biopython==1.81
      - celluloid==0.2.0
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorlog==6.8.0
      - contourpy==1.2.0
      - cycler==0.12.1
      - dna-features-viewer==3.1.3
      - dress==0.0.1
      - filelock==3.13.1
      - fonttools==4.46.0
      - fsspec==2023.12.1
      - geneticengine==0.8.5
      - greenlet==3.0.1
      - idna==3.6
      - ipykernel==6.27.1
      - jinja2==3.1.2
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.11.2
      - kiwisolver==1.4.5
      - loguru==0.7.2
      - mako==1.3.0
      - markdown-it-py==3.0.0
      - matplotlib==3.8.2
      - mdurl==0.1.2
      - mizani==0.9.3
      - mpmath==1.3.0
      - numpy==1.26.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - optuna==3.4.0
      - pandas==1.5.3
      - pangolin==1.0.2
      - patsy==0.5.4
      - pillow==10.1.0
      - plotnine==0.12.4
      - protobuf==3.19.6
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pyparsing==3.1.1
      - pyranges==0.0.131
      - pytest==7.4.3
      - referencing==0.31.1
      - requests==2.31.0
      - rich==13.7.0
      - rich-click==1.7.2
      - rpds-py==0.13.2
      - ruamel-yaml==0.18.5
      - ruamel-yaml-clib==0.2.8
      - seaborn==0.13.0
      - sqlalchemy==2.0.23
      - statsmodels==0.14.0
      - sympy==1.12
      - torch==2.1.1
      - tqdm==4.66.1
      - triton==2.1.0
      - tzdata==2023.3
      - urllib3==2.1.0
